spring.datasource.url=jdbc:mysql://localhost:3306/asset?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=123456

mybatis.mapper-locations=classpath:mappers/*.xml
server.port=9002

logging.level.root=WARN

logging.level.cn.tedu.asset.server=DEBUG

#命名规范不一致时自动识别
mybatis.configuration.map-underscore-to-camel-case=true

#设置单个上传文件大小限制
spring.servlet.multipart.max-file-size=100MB
# 设置总大小限制
spring.servlet.multipart.max-request-size=500MB
# 设置静态资源文件夹
spring.web.resources.static-locations=file:${file-path},classpath:static

# 保存文件的路径
file-path=d:/files